version: "3.7"

services:
    # image project
    laravel-crud-generator-app:
        container_name: laravel-crud-generator-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # nginx
    laravel-crud-generator-nginx:
        container_name: laravel-crud-generator-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "9100:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db pgsql
    laravel-crud-generator-pgsql:
        container_name: laravel-crud-generator-pgsql
        image: postgres:15.3
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/pgsql/dbdata:/var/lib/postgresql/data
        ports:
            - "5434:5432"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
